config/routes.rb
Rails.application.routes.draw do
  root 'games#new'
  get '/new', to: 'games#new'
  get '/result', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'open-uri'
require 'json'

class GamesController < ApplicationController
  def new
    @current_score = params[:score]
    @grid = generate_grid(10).join
    @start_time = Time.now
  end

  def score
    grid = params[:grid].split('')
    @attempt = params[:attempt]
    start_time = Time.parse(params[:start_time])
    end_time = Time.now
    @result = run_game(@attempt, grid, start_time, end_time)

    @total_score = 0
    @total_score = params[:score].to_f + @result[:score]
  end

  private

  def generate_grid(grid_size)
    grid = []
    alphabet = ('A'..'Z').to_a
    grid_size.times do
      grid << alphabet[rand(26)]
    end
    grid
  end

  def included?(guess, grid)
    guess.split('').all? { |letter| grid.include? letter }
  end

  def compute_score(attempt, time_taken)
    time_taken.positive? ? attempt.size * (1.0 - time_taken / 60.0) : 0
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(
      attempt, result[:translation], grid, result[:time]
    )
    result
  end

  def score_and_message(attempt, translation, grid, time)
    if translation
      if included?(attempt.upcase, grid)
        score = compute_score(attempt, time)
        [score, 'Well done!']
      else
        [0, 'Not in the grid!']
      end
    else
      [0, 'Not an english word!']
    end
  end

  def get_translation(word)
    url = "https://wagon-dictionary.herokuapp.com/#{word}"
    response_serialized = URI.open(url).read
    JSON.parse(response_serialized)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>WELCOME TO THE LONGEST WORD GAME</h1>

<h2>Grid: </h2>
 <% @grid.each_char do |letter| %>
 <h3 class="btn btn-primary"><%= letter %></h3>
 <% end %>

<form action="<%= result_path %>" method="get">
  <input type="text" name="attempt" class="form-text">
  <input type="hidden" name="grid" value="<%= @grid %>">
  <input type="hidden" name="start_time" value="<%= @start_time %>">
  <input type="hidden" name="score" value="<%= @current_score %>">
  <input type="submit" value="GO" class="btn btn-primary">
</form>

app/views/games/score.html.erb
<h1>Your result</h1>

<ul>
  <li>Attempt: <%= @attempt%></li>
  <%# <li>Translation: <%= @result[:translation]</li> %>
  <li>Time: <%= @result[:time]%></li>
  <li> <strong><%= @result[:message]%></strong> </li>
  <li>Score: <%= @result[:score]%></li>
  <li>Total score: <%= @total_score %> </li>
</ul>

<p class="btn btn-light text-decoration-none"> <%= link_to "Restart", new_path(score: @total_score) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <!-- <link rel="stylesheet" href=""> -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= yield %>
      </div>
    </div>
  </div>
  </body>
</html>